Name: JimmyTeam
IconPath: dekat.png
SoundPath: dekat.wav
Description: |
    Equipe de super Python avec function niveau 0
BrainsPackage: inGameTeams.python_level_0_jimmy
ScriptImplementation: python
AgentsBrainClasses:
    WarBase: WarBase.py
    WarExplorer: WarExplorer.py
    WarRocketLauncher: WarRocketLauncher.py
    WarKamikaze: WarKamikaze.py
    WarEngineer: WarEngineer.py
    WarTurret: WarTurret.py
